sudo rm -Rf /usr/lib/python2.5/site-packages/hamster/
sudo rm -f /usr/lib/bonobo/servers/Hamster_Applet.server
sudo rm -Rf /usr/share/hamster-applet/
sudo rm -Rf /usr/lib/hamster-applet/
sudo rm -Rf /usr/local/lib/python2.5/site-packages/hamster/
sudo rm -f /usr/local/lib/bonobo/servers/Hamster_Applet.server
sudo rm -Rf /usr/local/share/hamster-applet/
sudo rm -Rf /usr/local/lib/hamster-applet/
sudo rm -Rf /usr/lib/python2.6/dist-packages/hamster/
sudo rm -Rf /usr/local/lib/python2.6/dist-packages/hamster/
sudo rm -Rf /usr/local/lib/python2.6/site-packages/hamster/
sudo rm -Rf /usr/share/gnome/help/hamster-applet/
sudo rm -f /usr/bin/hamster-*
